[build]
builder = "nixpacks"
buildCommand = "echo 'No build step'"

[deploy]
startCommand = "sh /app/frontend/entrypoint.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
